apiVersion: v1
kind: Service
metadata:
  name: azurite-service  # Name of the service
spec:
  type: NodePort  # Type of service to expose the application (NodePort exposes the service on each Node's IP at a static port)
  ports:
    - name: blob  # Name of the Blob service port
      port: 10000  # Port on which the service is exposed
      targetPort: 10000  # Port on which the application is running inside the container
      protocol: TCP  # Protocol used for the service
    - name: queue  # Name of the Queue service port
      port: 10001  # Port on which the service is exposed
      targetPort: 10001  # Port on which the application is running inside the container
      protocol: TCP  # Protocol used for the service
    - name: table  # Name of the Table service port
      port: 10002  # Port on which the service is exposed
      targetPort: 10002  # Port on which the application is running inside the container
      protocol: TCP  # Protocol used for the service
  selector:
    app: azurite  # Selector to identify the pods managed by this service
