apiVersion: v1
kind: Service
metadata:
  name: azurefunctiontest-service  # Name of the service
spec:
  type: NodePort  # Type of service to expose the application (NodePort exposes the service on each Node's IP at a static port)
  ports:
    - port: 7071  # Port on which the service is exposed
      targetPort: 7071  # Port on which the application is running inside the container
      protocol: TCP  # Protocol used for the service
  selector:
    app: azurefunctiontest  # Selector to identify the pods managed by this service
