apiVersion: v1
kind: Service
metadata:
  name: azurite-service
spec:
  type: NodePort
  ports:
  - name: blob
    port: 10000
    targetPort: 10000
    protocol: TCP
  - name: queue
    port: 10001
    targetPort: 10001
    protocol: TCP
  - name: table
    port: 10002
    targetPort: 10002
    protocol: TCP
  selector:
    app: azurite
