apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite-deployment  # Name of the deployment
spec:
  replicas: 1  # Number of pod replicas to maintain
  selector:
    matchLabels:
      app: azurite  # Label selector to identify the pods managed by this deployment
  template:
    metadata:
      labels:
        app: azurite  # Labels to be assigned to the pods created by this deployment
    spec:
      containers:
        - name: azurite  # Name of the container
          image: mcr.microsoft.com/azure-storage/azurite  # Docker image to use for the container
          ports:
            - containerPort: 10000  # Port on which the container will listen for Blob service
            - containerPort: 10001  # Port on which the container will listen for Queue service
            - containerPort: 10002  # Port on which the container will listen for Table service
