apiVersion: v1
kind: Service
metadata:
  name: postgres-service  # Name of the service
spec:
  type: ClusterIP  # Type of service to expose the application (ClusterIP exposes the service on a cluster-internal IP)
  ports:
    - port: 5432  # Port on which the service is exposed
      targetPort: 5432  # Port on which the application is running inside the container
  selector:
    app: postgres  # Selector to identify the pods managed by this service
